server:
  port: 8000
  servlet:
    context-path: ""

logging:
  level:
    windsurfers-weather-api: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
  file:
    path: logs/

app:
  weatherbit:
    url: https://api.weatherbit.io/v2.0/forecast/daily