package windsurfersweatherapi.factory;

public class WeatherBitForecastResponseFactory {

  public static String pissouriWeatherBitForecastFullResponse() {
    return "{\n"
        + "  \"city_name\": \"Pissouri\",\n"
        + "  \"country_code\": \"CY\",\n"
        + "  \"data\": [\n"
        + "    {\n"
        + "      \"app_max_temp\": 25,\n"
        + "      \"app_min_temp\": 17.5,\n"
        + "      \"clouds\": 6,\n"
        + "      \"clouds_hi\": 13,\n"
        + "      \"clouds_low\": 2,\n"
        + "      \"clouds_mid\": 5,\n"
        + "      \"datetime\": \"2023-11-05\",\n"
        + "      \"dewpt\": 15,\n"
        + "      \"high_temp\": 25.1,\n"
        + "      \"low_temp\": 18.8,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 25.1,\n"
        + "      \"min_temp\": 17.5,\n"
        + "      \"moon_phase\": 0.394735,\n"
        + "      \"moon_phase_lunation\": 0.75,\n"
        + "      \"moonrise_ts\": 1699219563,\n"
        + "      \"moonset_ts\": 1699184177,\n"
        + "      \"ozone\": 270.2,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 987.8,\n"
        + "      \"rh\": 72,\n"
        + "      \"slp\": 1015.5,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699157593,\n"
        + "      \"sunset_ts\": 1699195959,\n"
        + "      \"temp\": 20.9,\n"
        + "      \"ts\": 1699135260,\n"
        + "      \"uv\": 3.1,\n"
        + "      \"valid_date\": \"2023-11-05\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c02d\",\n"
        + "        \"code\": 801,\n"
        + "        \"description\": \"Few clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"ESE\",\n"
        + "      \"wind_cdir_full\": \"east-southeast\",\n"
        + "      \"wind_dir\": 123,\n"
        + "      \"wind_gust_spd\": 4.6,\n"
        + "      \"wind_spd\": 2\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 25.3,\n"
        + "      \"app_min_temp\": 18.2,\n"
        + "      \"clouds\": 0,\n"
        + "      \"clouds_hi\": 0,\n"
        + "      \"clouds_low\": 18,\n"
        + "      \"clouds_mid\": 0,\n"
        + "      \"datetime\": \"2023-11-06\",\n"
        + "      \"dewpt\": 14.8,\n"
        + "      \"high_temp\": 25.1,\n"
        + "      \"low_temp\": 18.7,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 25.1,\n"
        + "      \"min_temp\": 18.8,\n"
        + "      \"moon_phase\": 0.303291,\n"
        + "      \"moon_phase_lunation\": 0.78,\n"
        + "      \"moonrise_ts\": 1699223052,\n"
        + "      \"moonset_ts\": 1699272165,\n"
        + "      \"ozone\": 259.6,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 989.4,\n"
        + "      \"rh\": 68,\n"
        + "      \"slp\": 1017.3,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699244049,\n"
        + "      \"sunset_ts\": 1699282309,\n"
        + "      \"temp\": 21.5,\n"
        + "      \"ts\": 1699221660,\n"
        + "      \"uv\": 4.5,\n"
        + "      \"valid_date\": \"2023-11-06\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c01d\",\n"
        + "        \"code\": 800,\n"
        + "        \"description\": \"Clear Sky\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"W\",\n"
        + "      \"wind_cdir_full\": \"west\",\n"
        + "      \"wind_dir\": 270,\n"
        + "      \"wind_gust_spd\": 7.3,\n"
        + "      \"wind_spd\": 3.3\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 25,\n"
        + "      \"app_min_temp\": 18.7,\n"
        + "      \"clouds\": 2,\n"
        + "      \"clouds_hi\": 0,\n"
        + "      \"clouds_low\": 22,\n"
        + "      \"clouds_mid\": 0,\n"
        + "      \"datetime\": \"2023-11-07\",\n"
        + "      \"dewpt\": 16,\n"
        + "      \"high_temp\": 25,\n"
        + "      \"low_temp\": 18.4,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 25,\n"
        + "      \"min_temp\": 18.7,\n"
        + "      \"moon_phase\": 0.218722,\n"
        + "      \"moon_phase_lunation\": 0.82,\n"
        + "      \"moonrise_ts\": 1699312866,\n"
        + "      \"moonset_ts\": 1699360022,\n"
        + "      \"ozone\": 256.1,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 991.6,\n"
        + "      \"rh\": 74,\n"
        + "      \"slp\": 1019.5,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699330505,\n"
        + "      \"sunset_ts\": 1699368659,\n"
        + "      \"temp\": 21.4,\n"
        + "      \"ts\": 1699308060,\n"
        + "      \"uv\": 4.1,\n"
        + "      \"valid_date\": \"2023-11-07\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c02d\",\n"
        + "        \"code\": 801,\n"
        + "        \"description\": \"Few clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"S\",\n"
        + "      \"wind_cdir_full\": \"south\",\n"
        + "      \"wind_dir\": 185,\n"
        + "      \"wind_gust_spd\": 5.8,\n"
        + "      \"wind_spd\": 2.4\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 24.4,\n"
        + "      \"app_min_temp\": 16.8,\n"
        + "      \"clouds\": 1,\n"
        + "      \"clouds_hi\": 2,\n"
        + "      \"clouds_low\": 12,\n"
        + "      \"clouds_mid\": 0,\n"
        + "      \"datetime\": \"2023-11-08\",\n"
        + "      \"dewpt\": 15.3,\n"
        + "      \"high_temp\": 24.3,\n"
        + "      \"low_temp\": 15.1,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 24.3,\n"
        + "      \"min_temp\": 16.8,\n"
        + "      \"moon_phase\": 0.143755,\n"
        + "      \"moon_phase_lunation\": 0.85,\n"
        + "      \"moonrise_ts\": 1699399266,\n"
        + "      \"moonset_ts\": 1699447824,\n"
        + "      \"ozone\": 260.6,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 985.9,\n"
        + "      \"rh\": 75,\n"
        + "      \"slp\": 1004.4,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699416962,\n"
        + "      \"sunset_ts\": 1699455012,\n"
        + "      \"temp\": 20.3,\n"
        + "      \"ts\": 1699394460,\n"
        + "      \"uv\": 4.4,\n"
        + "      \"valid_date\": \"2023-11-08\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c01d\",\n"
        + "        \"code\": 800,\n"
        + "        \"description\": \"Clear Sky\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SE\",\n"
        + "      \"wind_cdir_full\": \"southeast\",\n"
        + "      \"wind_dir\": 142,\n"
        + "      \"wind_gust_spd\": 3.2,\n"
        + "      \"wind_spd\": 1.9\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 23.2,\n"
        + "      \"app_min_temp\": 15.1,\n"
        + "      \"clouds\": 25,\n"
        + "      \"clouds_hi\": 77,\n"
        + "      \"clouds_low\": 0,\n"
        + "      \"clouds_mid\": 11,\n"
        + "      \"datetime\": \"2023-11-09\",\n"
        + "      \"dewpt\": 13.1,\n"
        + "      \"high_temp\": 23.4,\n"
        + "      \"low_temp\": 16.8,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 23.4,\n"
        + "      \"min_temp\": 15.1,\n"
        + "      \"moon_phase\": 0.0813748,\n"
        + "      \"moon_phase_lunation\": 0.89,\n"
        + "      \"moonrise_ts\": 1699489046,\n"
        + "      \"moonset_ts\": 1699535644,\n"
        + "      \"ozone\": 265.4,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 976.1,\n"
        + "      \"rh\": 70,\n"
        + "      \"slp\": 979,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699503418,\n"
        + "      \"sunset_ts\": 1699541366,\n"
        + "      \"temp\": 19,\n"
        + "      \"ts\": 1699480860,\n"
        + "      \"uv\": 3.6,\n"
        + "      \"valid_date\": \"2023-11-09\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c02d\",\n"
        + "        \"code\": 802,\n"
        + "        \"description\": \"Scattered clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SSE\",\n"
        + "      \"wind_cdir_full\": \"south-southeast\",\n"
        + "      \"wind_dir\": 158,\n"
        + "      \"wind_gust_spd\": 1.6,\n"
        + "      \"wind_spd\": 1.8\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 22.8,\n"
        + "      \"app_min_temp\": 16.8,\n"
        + "      \"clouds\": 68,\n"
        + "      \"clouds_hi\": 100,\n"
        + "      \"clouds_low\": 0,\n"
        + "      \"clouds_mid\": 61,\n"
        + "      \"datetime\": \"2023-11-10\",\n"
        + "      \"dewpt\": 14.1,\n"
        + "      \"high_temp\": 23,\n"
        + "      \"low_temp\": 17.1,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 23,\n"
        + "      \"min_temp\": 16.8,\n"
        + "      \"moon_phase\": 0.0347566,\n"
        + "      \"moon_phase_lunation\": 0.92,\n"
        + "      \"moonrise_ts\": 1699578851,\n"
        + "      \"moonset_ts\": 1699623556,\n"
        + "      \"ozone\": 274.1,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 977.1,\n"
        + "      \"rh\": 74,\n"
        + "      \"slp\": 979.9,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699589875,\n"
        + "      \"sunset_ts\": 1699627721,\n"
        + "      \"temp\": 19,\n"
        + "      \"ts\": 1699567260,\n"
        + "      \"uv\": 4.4,\n"
        + "      \"valid_date\": \"2023-11-10\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c03d\",\n"
        + "        \"code\": 803,\n"
        + "        \"description\": \"Broken clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"E\",\n"
        + "      \"wind_cdir_full\": \"east\",\n"
        + "      \"wind_dir\": 101,\n"
        + "      \"wind_gust_spd\": 1,\n"
        + "      \"wind_spd\": 1.1\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 23.1,\n"
        + "      \"app_min_temp\": 17.1,\n"
        + "      \"clouds\": 35,\n"
        + "      \"clouds_hi\": 66,\n"
        + "      \"clouds_low\": 0,\n"
        + "      \"clouds_mid\": 31,\n"
        + "      \"datetime\": \"2023-11-11\",\n"
        + "      \"dewpt\": 11.8,\n"
        + "      \"high_temp\": 23.7,\n"
        + "      \"low_temp\": 15.8,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 23.7,\n"
        + "      \"min_temp\": 17.1,\n"
        + "      \"moon_phase\": 0.00704502,\n"
        + "      \"moon_phase_lunation\": 0.95,\n"
        + "      \"moonrise_ts\": 1699668745,\n"
        + "      \"moonset_ts\": 1699711647,\n"
        + "      \"ozone\": 286.6,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 976.2,\n"
        + "      \"rh\": 63,\n"
        + "      \"slp\": 979,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699676333,\n"
        + "      \"sunset_ts\": 1699714079,\n"
        + "      \"temp\": 19.6,\n"
        + "      \"ts\": 1699653660,\n"
        + "      \"uv\": 4.4,\n"
        + "      \"valid_date\": \"2023-11-11\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c02d\",\n"
        + "        \"code\": 802,\n"
        + "        \"description\": \"Scattered clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SW\",\n"
        + "      \"wind_cdir_full\": \"southwest\",\n"
        + "      \"wind_dir\": 216,\n"
        + "      \"wind_gust_spd\": 1.2,\n"
        + "      \"wind_spd\": 1.2\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 22.6,\n"
        + "      \"app_min_temp\": 15.8,\n"
        + "      \"clouds\": 11,\n"
        + "      \"clouds_hi\": 44,\n"
        + "      \"clouds_low\": 0,\n"
        + "      \"clouds_mid\": 0,\n"
        + "      \"datetime\": \"2023-11-12\",\n"
        + "      \"dewpt\": 11.2,\n"
        + "      \"high_temp\": 23,\n"
        + "      \"low_temp\": 15.6,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 23,\n"
        + "      \"min_temp\": 15.8,\n"
        + "      \"moon_phase\": 0.00101482,\n"
        + "      \"moon_phase_lunation\": 0.99,\n"
        + "      \"moonrise_ts\": 1699758787,\n"
        + "      \"moonset_ts\": 1699800020,\n"
        + "      \"ozone\": 289.4,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 976.6,\n"
        + "      \"rh\": 62,\n"
        + "      \"slp\": 979.4,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699762790,\n"
        + "      \"sunset_ts\": 1699800437,\n"
        + "      \"temp\": 18.8,\n"
        + "      \"ts\": 1699740060,\n"
        + "      \"uv\": 4.3,\n"
        + "      \"valid_date\": \"2023-11-12\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c02d\",\n"
        + "        \"code\": 801,\n"
        + "        \"description\": \"Few clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SW\",\n"
        + "      \"wind_cdir_full\": \"southwest\",\n"
        + "      \"wind_dir\": 232,\n"
        + "      \"wind_gust_spd\": 2.2,\n"
        + "      \"wind_spd\": 2.3\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 22.1,\n"
        + "      \"app_min_temp\": 15.6,\n"
        + "      \"clouds\": 5,\n"
        + "      \"clouds_hi\": 22,\n"
        + "      \"clouds_low\": 0,\n"
        + "      \"clouds_mid\": 0,\n"
        + "      \"datetime\": \"2023-11-13\",\n"
        + "      \"dewpt\": 11.6,\n"
        + "      \"high_temp\": 22.4,\n"
        + "      \"low_temp\": 15.2,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 22.4,\n"
        + "      \"min_temp\": 15.6,\n"
        + "      \"moon_phase\": 0.018674,\n"
        + "      \"moon_phase_lunation\": 0.02,\n"
        + "      \"moonrise_ts\": 1699849013,\n"
        + "      \"moonset_ts\": 1699888792,\n"
        + "      \"ozone\": 279.3,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 978.8,\n"
        + "      \"rh\": 66,\n"
        + "      \"slp\": 981.6,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699849247,\n"
        + "      \"sunset_ts\": 1699886798,\n"
        + "      \"temp\": 18.3,\n"
        + "      \"ts\": 1699826460,\n"
        + "      \"uv\": 4.3,\n"
        + "      \"valid_date\": \"2023-11-13\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c02d\",\n"
        + "        \"code\": 801,\n"
        + "        \"description\": \"Few clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"S\",\n"
        + "      \"wind_cdir_full\": \"south\",\n"
        + "      \"wind_dir\": 183,\n"
        + "      \"wind_gust_spd\": 1.8,\n"
        + "      \"wind_spd\": 1.8\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 21.9,\n"
        + "      \"app_min_temp\": 15.2,\n"
        + "      \"clouds\": 14,\n"
        + "      \"clouds_hi\": 57,\n"
        + "      \"clouds_low\": 0,\n"
        + "      \"clouds_mid\": 0,\n"
        + "      \"datetime\": \"2023-11-14\",\n"
        + "      \"dewpt\": 10.5,\n"
        + "      \"high_temp\": 22.4,\n"
        + "      \"low_temp\": 15.3,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 22.4,\n"
        + "      \"min_temp\": 15.2,\n"
        + "      \"moon_phase\": 0.0608709,\n"
        + "      \"moon_phase_lunation\": 0.05,\n"
        + "      \"moonrise_ts\": 1699939404,\n"
        + "      \"moonset_ts\": 1699978073,\n"
        + "      \"ozone\": 281.4,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 977,\n"
        + "      \"rh\": 63,\n"
        + "      \"slp\": 979.9,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1699935705,\n"
        + "      \"sunset_ts\": 1699973160,\n"
        + "      \"temp\": 17.9,\n"
        + "      \"ts\": 1699912860,\n"
        + "      \"uv\": 4.2,\n"
        + "      \"valid_date\": \"2023-11-14\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c02d\",\n"
        + "        \"code\": 801,\n"
        + "        \"description\": \"Few clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SSE\",\n"
        + "      \"wind_cdir_full\": \"south-southeast\",\n"
        + "      \"wind_dir\": 156,\n"
        + "      \"wind_gust_spd\": 1.5,\n"
        + "      \"wind_spd\": 1.7\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 21.9,\n"
        + "      \"app_min_temp\": 15.3,\n"
        + "      \"clouds\": 51,\n"
        + "      \"clouds_hi\": 52,\n"
        + "      \"clouds_low\": 1,\n"
        + "      \"clouds_mid\": 50,\n"
        + "      \"datetime\": \"2023-11-15\",\n"
        + "      \"dewpt\": 6.4,\n"
        + "      \"high_temp\": 24.9,\n"
        + "      \"low_temp\": 14.1,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 24.9,\n"
        + "      \"min_temp\": 15.3,\n"
        + "      \"moon_phase\": 0.126937,\n"
        + "      \"moon_phase_lunation\": 0.09,\n"
        + "      \"moonrise_ts\": 1700029854,\n"
        + "      \"moonset_ts\": 1700067912,\n"
        + "      \"ozone\": 284.5,\n"
        + "      \"pop\": 0,\n"
        + "      \"precip\": 0,\n"
        + "      \"pres\": 972,\n"
        + "      \"rh\": 45,\n"
        + "      \"slp\": 974.8,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1700022162,\n"
        + "      \"sunset_ts\": 1700059523,\n"
        + "      \"temp\": 18.9,\n"
        + "      \"ts\": 1699999260,\n"
        + "      \"uv\": 4.2,\n"
        + "      \"valid_date\": \"2023-11-15\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c03d\",\n"
        + "        \"code\": 803,\n"
        + "        \"description\": \"Broken clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"ESE\",\n"
        + "      \"wind_cdir_full\": \"east-southeast\",\n"
        + "      \"wind_dir\": 110,\n"
        + "      \"wind_gust_spd\": 1.5,\n"
        + "      \"wind_spd\": 2\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 18.1,\n"
        + "      \"app_min_temp\": 15.7,\n"
        + "      \"clouds\": 54,\n"
        + "      \"clouds_hi\": 50,\n"
        + "      \"clouds_low\": 7,\n"
        + "      \"clouds_mid\": 50,\n"
        + "      \"datetime\": \"2023-11-16\",\n"
        + "      \"dewpt\": 10.4,\n"
        + "      \"high_temp\": 19.9,\n"
        + "      \"low_temp\": 14,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 19.9,\n"
        + "      \"min_temp\": 14.1,\n"
        + "      \"moon_phase\": 0.214398,\n"
        + "      \"moon_phase_lunation\": 0.12,\n"
        + "      \"moonrise_ts\": 1700120170,\n"
        + "      \"moonset_ts\": 1700158235,\n"
        + "      \"ozone\": 309.1,\n"
        + "      \"pop\": 90,\n"
        + "      \"precip\": 14.125,\n"
        + "      \"pres\": 969.8,\n"
        + "      \"rh\": 66,\n"
        + "      \"slp\": 972.6,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1700108620,\n"
        + "      \"sunset_ts\": 1700145889,\n"
        + "      \"temp\": 16.9,\n"
        + "      \"ts\": 1700085660,\n"
        + "      \"uv\": 4.2,\n"
        + "      \"valid_date\": \"2023-11-16\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"r02d\",\n"
        + "        \"code\": 501,\n"
        + "        \"description\": \"Moderate rain\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SSW\",\n"
        + "      \"wind_cdir_full\": \"south-southwest\",\n"
        + "      \"wind_dir\": 212,\n"
        + "      \"wind_gust_spd\": 6.5,\n"
        + "      \"wind_spd\": 5.9\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 17.9,\n"
        + "      \"app_min_temp\": 15.5,\n"
        + "      \"clouds\": 100,\n"
        + "      \"clouds_hi\": 100,\n"
        + "      \"clouds_low\": 51,\n"
        + "      \"clouds_mid\": 83,\n"
        + "      \"datetime\": \"2023-11-17\",\n"
        + "      \"dewpt\": 9.3,\n"
        + "      \"high_temp\": 20.4,\n"
        + "      \"low_temp\": 13.9,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 20.4,\n"
        + "      \"min_temp\": 14,\n"
        + "      \"moon_phase\": 0.318904,\n"
        + "      \"moon_phase_lunation\": 0.16,\n"
        + "      \"moonrise_ts\": 1700210133,\n"
        + "      \"moonset_ts\": 1700248851,\n"
        + "      \"ozone\": 279.9,\n"
        + "      \"pop\": 25,\n"
        + "      \"precip\": 0.875,\n"
        + "      \"pres\": 976.3,\n"
        + "      \"rh\": 61,\n"
        + "      \"slp\": 979.1,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1700195077,\n"
        + "      \"sunset_ts\": 1700232256,\n"
        + "      \"temp\": 17,\n"
        + "      \"ts\": 1700172060,\n"
        + "      \"uv\": 4.1,\n"
        + "      \"valid_date\": \"2023-11-17\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c04d\",\n"
        + "        \"code\": 804,\n"
        + "        \"description\": \"Overcast clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SW\",\n"
        + "      \"wind_cdir_full\": \"southwest\",\n"
        + "      \"wind_dir\": 228,\n"
        + "      \"wind_gust_spd\": 4.7,\n"
        + "      \"wind_spd\": 3.5\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 20.7,\n"
        + "      \"app_min_temp\": 15.4,\n"
        + "      \"clouds\": 66,\n"
        + "      \"clouds_hi\": 100,\n"
        + "      \"clouds_low\": 11,\n"
        + "      \"clouds_mid\": 66,\n"
        + "      \"datetime\": \"2023-11-18\",\n"
        + "      \"dewpt\": 10.1,\n"
        + "      \"high_temp\": 23.5,\n"
        + "      \"low_temp\": 14.2,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 23.5,\n"
        + "      \"min_temp\": 13.9,\n"
        + "      \"moon_phase\": 0.434542,\n"
        + "      \"moon_phase_lunation\": 0.19,\n"
        + "      \"moonrise_ts\": 1700299608,\n"
        + "      \"moonset_ts\": 1700339546,\n"
        + "      \"ozone\": 293.9,\n"
        + "      \"pop\": 20,\n"
        + "      \"precip\": 0.0625,\n"
        + "      \"pres\": 975.3,\n"
        + "      \"rh\": 61,\n"
        + "      \"slp\": 978.1,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1700281535,\n"
        + "      \"sunset_ts\": 1700318625,\n"
        + "      \"temp\": 18.4,\n"
        + "      \"ts\": 1700258460,\n"
        + "      \"uv\": 4.1,\n"
        + "      \"valid_date\": \"2023-11-18\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c03d\",\n"
        + "        \"code\": 803,\n"
        + "        \"description\": \"Broken clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SE\",\n"
        + "      \"wind_cdir_full\": \"southeast\",\n"
        + "      \"wind_dir\": 138,\n"
        + "      \"wind_gust_spd\": 3.2,\n"
        + "      \"wind_spd\": 3.2\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 20.3,\n"
        + "      \"app_min_temp\": 15.8,\n"
        + "      \"clouds\": 10,\n"
        + "      \"clouds_hi\": 0,\n"
        + "      \"clouds_low\": 10,\n"
        + "      \"clouds_mid\": 0,\n"
        + "      \"datetime\": \"2023-11-19\",\n"
        + "      \"dewpt\": 11.7,\n"
        + "      \"high_temp\": 22.7,\n"
        + "      \"low_temp\": 14.4,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 22.7,\n"
        + "      \"min_temp\": 14.2,\n"
        + "      \"moon_phase\": 0.554423,\n"
        + "      \"moon_phase_lunation\": 0.22,\n"
        + "      \"moonrise_ts\": 1700388594,\n"
        + "      \"moonset_ts\": 1700430181,\n"
        + "      \"ozone\": 294.6,\n"
        + "      \"pop\": 25,\n"
        + "      \"precip\": 1,\n"
        + "      \"pres\": 972.8,\n"
        + "      \"rh\": 67,\n"
        + "      \"slp\": 975.6,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1700367992,\n"
        + "      \"sunset_ts\": 1700404995,\n"
        + "      \"temp\": 18.2,\n"
        + "      \"ts\": 1700344860,\n"
        + "      \"uv\": 4.1,\n"
        + "      \"valid_date\": \"2023-11-19\",\n"
        + "      \"vis\": 23.536,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c02d\",\n"
        + "        \"code\": 801,\n"
        + "        \"description\": \"Few clouds\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SE\",\n"
        + "      \"wind_cdir_full\": \"southeast\",\n"
        + "      \"wind_dir\": 125,\n"
        + "      \"wind_gust_spd\": 2.7,\n"
        + "      \"wind_spd\": 3.2\n"
        + "    },\n"
        + "    {\n"
        + "      \"app_max_temp\": 19.2,\n"
        + "      \"app_min_temp\": 16,\n"
        + "      \"clouds\": 0,\n"
        + "      \"clouds_hi\": 1,\n"
        + "      \"clouds_low\": 0,\n"
        + "      \"clouds_mid\": 0,\n"
        + "      \"datetime\": \"2023-11-20\",\n"
        + "      \"dewpt\": 10.9,\n"
        + "      \"high_temp\": 21.6,\n"
        + "      \"low_temp\": 14.6,\n"
        + "      \"max_dhi\": null,\n"
        + "      \"max_temp\": 21.6,\n"
        + "      \"min_temp\": 14.4,\n"
        + "      \"moon_phase\": 0.671302,\n"
        + "      \"moon_phase_lunation\": 0.26,\n"
        + "      \"moonrise_ts\": 1700477180,\n"
        + "      \"moonset_ts\": 1700434317,\n"
        + "      \"ozone\": 273.5,\n"
        + "      \"pop\": 10,\n"
        + "      \"precip\": 0.25,\n"
        + "      \"pres\": 972.5,\n"
        + "      \"rh\": 65,\n"
        + "      \"slp\": 975.4,\n"
        + "      \"snow\": 0,\n"
        + "      \"snow_depth\": 0,\n"
        + "      \"sunrise_ts\": 1700454449,\n"
        + "      \"sunset_ts\": 1700491368,\n"
        + "      \"temp\": 17.8,\n"
        + "      \"ts\": 1700431260,\n"
        + "      \"uv\": 4,\n"
        + "      \"valid_date\": \"2023-11-20\",\n"
        + "      \"vis\": 24.128,\n"
        + "      \"weather\": {\n"
        + "        \"icon\": \"c01d\",\n"
        + "        \"code\": 800,\n"
        + "        \"description\": \"Clear Sky\"\n"
        + "      },\n"
        + "      \"wind_cdir\": \"SE\",\n"
        + "      \"wind_cdir_full\": \"southeast\",\n"
        + "      \"wind_dir\": 129,\n"
        + "      \"wind_gust_spd\": 3.4,\n"
        + "      \"wind_spd\": 3.7\n"
        + "    }\n"
        + "  ],\n"
        + "  \"lat\": \"34.66942\",\n"
        + "  \"lon\": \"32.70132\",\n"
        + "  \"state_code\": \"05\",\n"
        + "  \"timezone\": \"Asia/Nicosia\"\n"
        + "}";
  }

  public static String pissouriWeatherBitForecastShortResponse() {
    return "{\n" +
        "  \"city_name\": \"Pissouri\",\n" +
        "  \"country_code\": \"CY\",\n" +
        "  \"data\": [\n" +
        "    {\n" +
        "      \"app_max_temp\": 24.6,\n" +
        "      \"app_min_temp\": 18.2,\n" +
        "      \"clouds\": 0,\n" +
        "      \"clouds_hi\": 0,\n" +
        "      \"clouds_low\": 23,\n" +
        "      \"clouds_mid\": 0,\n" +
        "      \"datetime\": \"2023-11-04\",\n" +
        "      \"dewpt\": 17.1,\n" +
        "      \"high_temp\": 24.3,\n" +
        "      \"low_temp\": 18.4,\n" +
        "      \"max_dhi\": null,\n" +
        "      \"max_temp\": 24.3,\n" +
        "      \"min_temp\": 18.2,\n" +
        "      \"moon_phase\": 0.490503,\n" +
        "      \"moon_phase_lunation\": 0.72,\n" +
        "      \"moonrise_ts\": 1699129593,\n" +
        "      \"moonset_ts\": 1699095974,\n" +
        "      \"ozone\": 275.9,\n" +
        "      \"pop\": 0,\n" +
        "      \"precip\": 0,\n" +
        "      \"pres\": 987.4,\n" +
        "      \"rh\": 81,\n" +
        "      \"slp\": 1015.1,\n" +
        "      \"snow\": 0,\n" +
        "      \"snow_depth\": 0,\n" +
        "      \"sunrise_ts\": 1699071137,\n" +
        "      \"sunset_ts\": 1699109611,\n" +
        "      \"temp\": 21.1,\n" +
        "      \"ts\": 1699048860,\n" +
        "      \"uv\": 4.5,\n" +
        "      \"valid_date\": \"2023-11-04\",\n" +
        "      \"vis\": 24.128,\n" +
        "      \"weather\": {\n" +
        "        \"description\": \"Clear Sky\",\n" +
        "        \"code\": 800,\n" +
        "        \"icon\": \"c01d\"\n" +
        "      },\n" +
        "      \"wind_cdir\": \"ESE\",\n" +
        "      \"wind_cdir_full\": \"east-southeast\",\n" +
        "      \"wind_dir\": 108,\n" +
        "      \"wind_gust_spd\": 3.8,\n" +
        "      \"wind_spd\": 1.7\n" +
        "    },\n" +
        "    {\n" +
        "      \"app_max_temp\": 25,\n" +
        "      \"app_min_temp\": 18.4,\n" +
        "      \"clouds\": 8,\n" +
        "      \"clouds_hi\": 18,\n" +
        "      \"clouds_low\": 9,\n" +
        "      \"clouds_mid\": 5,\n" +
        "      \"datetime\": \"2023-11-05\",\n" +
        "      \"dewpt\": 16.7,\n" +
        "      \"high_temp\": 24.9,\n" +
        "      \"low_temp\": 18.9,\n" +
        "      \"max_dhi\": null,\n" +
        "      \"max_temp\": 24.9,\n" +
        "      \"min_temp\": 18.4,\n" +
        "      \"moon_phase\": 0.394735,\n" +
        "      \"moon_phase_lunation\": 0.75,\n" +
        "      \"moonrise_ts\": 1699219563,\n" +
        "      \"moonset_ts\": 1699184177,\n" +
        "      \"ozone\": 280.6,\n" +
        "      \"pop\": 0,\n" +
        "      \"precip\": 0,\n" +
        "      \"pres\": 988,\n" +
        "      \"rh\": 79,\n" +
        "      \"slp\": 1015.8,\n" +
        "      \"snow\": 0,\n" +
        "      \"snow_depth\": 0,\n" +
        "      \"sunrise_ts\": 1699157593,\n" +
        "      \"sunset_ts\": 1699195959,\n" +
        "      \"temp\": 21.1,\n" +
        "      \"ts\": 1699135260,\n" +
        "      \"uv\": 4.4,\n" +
        "      \"valid_date\": \"2023-11-05\",\n" +
        "      \"vis\": 24.128,\n" +
        "      \"weather\": {\n" +
        "        \"description\": \"Few clouds\",\n" +
        "        \"code\": 801,\n" +
        "        \"icon\": \"c02d\"\n" +
        "      },\n" +
        "      \"wind_cdir\": \"ESE\",\n" +
        "      \"wind_cdir_full\": \"east-southeast\",\n" +
        "      \"wind_dir\": 108,\n" +
        "      \"wind_gust_spd\": 3.8,\n" +
        "      \"wind_spd\": 1.7\n" +
        "    }\n" +
        "  ],\n" +
        "  \"lat\": \"34.66942\",\n" +
        "  \"lon\": \"32.70132\",\n" +
        "  \"state_code\": \"05\",\n" +
        "  \"timezone\": \"Asia/Nicosia\"\n" +
        "}";
  }
}
